- name: Install Apache2 on Slave 1
  hosts: slave
  become: true
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present

- name: Install Nginx on Slave 2
  hosts: slave 
  become: true
  tasks:
    - name: Install nginx  
      apt:  
        name: nginx
        state: present  
 
